param_server:
  ros__parameters:
    name:
      # publish
      grid: "/decision_interface/map/grid"
      cost: "/decision_interface/map/cost"
      status: "/decision_interface/status"
      transformed_map: "/decision_interface/transformed_map"
      # subscribe
      control:
        velocity: "/decision_interface/control/velocity"
        rotation: "/decision_interface/control/rotation"
        gimbal: "/decision_interface/control/gimbal"
      lidar: "/livox/lidar"
      # other
      node: "decision_interface"
      frame:
        map: "yaw_link"
    # process config
    generate:
      cost_map: false
    lidar:
      livox_frames: 1
    grid:
      resolution: 0.05
      grid_width: 6.06
      lidar_blind: 0.8
      z_wight: 3.1
    filter:
      ground_height: 0.2

